In [1]:
# test

In [2]:
import numpy as np

In [3]:
a = np.array([[0,1, 2], [3,4,5]])

In [4]:
print a

[[0 1 2]
 [3 4 5]]


In [5]:
a[(0,1)]

1

In [7]:
a[[(0,1), (0,2)]]

array([0, 5])

In [9]:
np.indices??