In [2]:
# test

In [3]:
import numpy as np

In [4]:
a = np.array([[0,1, 2], [3,4,5]])

In [5]:
print a

[[0 1 2]
 [3 4 5]]


In [6]:
a[(0,1)]

1

In [7]:
a[[(0,1), (0,2)]]

array([0, 5])

In [8]:
np.indices??

In [9]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
np.take(a, (0,1, 5))

array([0, 1, 5])

In [17]:
np.take(a, (0, 1), axis=1)

array([[0, 1],
       [3, 4]])

In [24]:
a = np.array(range(0, 5)).reshape((1, 5))

In [25]:

print a

[[0 1 2 3 4]]


In [22]:
b = np.array([1,0, 1, 0]).reshape((4, 1))

In [26]:
print a * b

[[0 1 2 3 4]
 [0 0 0 0 0]
 [0 1 2 3 4]
 [0 0 0 0 0]]


In [28]:
print b.T * a.T

[[0 0 0 0]
 [1 0 1 0]
 [2 0 2 0]
 [3 0 3 0]
 [4 0 4 0]]


In [33]:
(a > 0).astype(np.float32)

array([[ 0.,  1.,  1.,  1.,  1.]], dtype=float32)

In [34]:
 y = np.arange(35).reshape(5,7)

In [38]:
print y
y[1:5:2,::3]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[ 7, 10, 13],
       [21, 24, 27]])

In [37]:
y[:, [1,2]]

array([[ 1,  2],
       [ 8,  9],
       [15, 16],
       [22, 23],
       [29, 30]])

In [44]:
z = np.array(range(0, 75)).reshape(5, 5, 3)

In [45]:
print z

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]

 [[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]]


In [48]:
y[[1,2], [3,4]] = -1

In [49]:
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, -1, 11, 12, 13],
       [14, 15, 16, 17, -1, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [50]:
print y.shape

(5, 7)


In [51]:
z[[1,2], :, [1, 2]] = -1

In [52]:
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, -1, 17],
        [18, -1, 20],
        [21, -1, 23],
        [24, -1, 26],
        [27, -1, 29]],

       [[30, 31, -1],
        [33, 34, -1],
        [36, 37, -1],
        [39, 40, -1],
        [42, 43, -1]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]],

       [[60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74]]])

In [63]:
z[:, 0:3, [2, 1, 0]] = -5

In [64]:
print z

[[[-5 -5 -5]
  [-5 -5 -5]
  [-5 -5 -5]
  [ 9 10 11]
  [12 13 14]]

 [[-5 -5 -5]
  [-5 -5 -5]
  [-5 -5 -5]
  [24 -1 26]
  [27 -1 29]]

 [[-5 -5 -5]
  [-5 -5 -5]
  [-5 -5 -5]
  [39 40 -1]
  [42 43 -1]]

 [[-5 -5 -5]
  [-5 -5 -5]
  [-5 -5 -5]
  [54 55 56]
  [57 58 59]]

 [[-5 -5 -5]
  [-5 -5 -5]
  [-5 -5 -5]
  [69 70 71]
  [72 73 74]]]
